### PR TITLE
Correctly apply hr margin to top and bottom

### PR DESCRIPTION
**Pull request by nikitasol**
Update margin. It was modified at some point to be direction explicit and now only corresponds to top and bottom.

### CODE REVIEW

**Comment by DanielRuf** [comment]
This change makes not much sense to me. In email templates margin should be only applied to top and bottom (the space for hr) not left or right as this will produce issues with the table.

**Comment by DanielRuf** [comment]
Also the variable name itself is very general. Can you show the relevant code part where this was changed?

**Comment by nikitasol** [comment]
Yes, of course @DanielRuf. This is referenced in the commit on foundation-emails develop branch: https://github.com/foundation/foundation-emails/pull/1013/commits/47c58238a9723b3ad443bfd3008fe4b8274e6a24

The code responsible for generating styles for hr line is defined in this mixin:

```SCSS
@mixin h-line($align: $hr-align, $width: $hr-width, $border: $hr-border, $margin: nth($hr-margin, 1)) {
  @at-root {
    td.columns & table,
    td.column  & table,
    th.columns & table,
    th.column  & table {
      width: auto;
    }
  }

  th {
    padding-bottom: $margin;
    @if $align == 'left' {
      text-align: left;
    } @elseif $align == 'right' {
      text-align: right;
    } @else {
      text-align: center;
    }
  }

    table {
      display: inline-block;
      margin: 0;
      Margin: 0;
    }

      td {
        width: $width;
        height: 0;
        padding-top: $margin;
        clear: both;
        border-top: 0;
        border-right: 0;
        border-bottom: $border;
        border-left: 0;
        font-size: 0;
        line-height: 0;
      }
}
```

which is later included here:
```SCSS
// Horizontal rule
table.hr,
table.h-line {
  @include h-line($hr-align, $hr-width, $hr-border, $hr-margin);
}
````

At the moment this doesn't work and the styles are not being applied. The $margin: nth($hr-margin, 1) won't work in the mixin, because it is included later through $hr-margin). We can fix the include formula changing $hr-margin to  $margin: nth($hr-margin, 1), but I cannot see any place where left and right margin value is being used, so I think it is a cleaner solution to change the value in the template _settings.

I have tested on clean install of foundation-emails and at the moment adding <hr/> just creates a browser specific horizontal divider with no user specific styles.

Applying these two commits brings back the functionality:
1. #63 
2. https://github.com/foundation/foundation-emails/pull/1013/commits/47c58238a9723b3ad443bfd3008fe4b8274e6a24

**Comment by DanielRuf** [comment]
> nikitasol wants to merge 1 commit into foundation:master from nikitasol:master

Please use a separate branch in your fork next time, otherwise there can be conflicts with the master branch (and it is also an anit-pattern) ;-)

**Pull request merged**
