### PR TITLE
Bugfix - Update Gulp version to "^4.0.0"

### PR DESCRIPTION
**Pull request by frankievx**
This request fixes the new email project creation error regarding the bad package.json gulp link.

### CODE REVIEW

**Comment by phuocle** [comment]
Please merge this. It take me a lot of time to know this small bug.

**Comment by jayliu50** [comment]
Will fix this issue: https://github.com/zurb/foundation-emails/issues/934

**Comment by browserbully** [comment]
Can someone with `write access` merge this? Please and thank you!

**Comment by jsphkm** [comment]
bump

**Comment by pbpyrojust** [comment]
Please for the love of God merge this fix. A small bug that will save a lot of headaches, StackOverflow and Google searches.

**Comment by venusvavadiya** [comment]
Please merge this guys! Took some time to figure this out.

**Comment by santiycr** [comment]
bump bump

**Pull request merged**
